# Default values for Neo4j.
# This is a YAML-formatted file.

neo4j:
  # If not set or empty a random password will be generated
  password: ""
  edition: "community"

# The volumeClaimTemplates will provide stable storage
volumeClaimTemplates:
  # Using "manual" storage class prevents automatic provisioning and only makes use of manually defined PVCs
  useDefaultStorageClass: false
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  # Amount of disk storage to request. Some cloud providers allocate IOPS proportionally to disk size, if that is the case it may be necessary to set the disk request
  # to a significantly larger value than is required just to store the database files.
  # We recommend a disk size of at least 1Ti for performance or load testing and at least 100Gi for development work.
  request: 100Gi


# Specs for the Neo4j docker image
image:
  imagePullPolicy: IfNotPresent

### Neo4j Configuration

# Neo4j configuration (yaml format)
config:
  dbms.config.strict_validation: "true"

# Neo4j configuration (text format)
configImport: |
  # neo4j.conf key=value properties file contents can be included here.
  # multi-line text must be indented correctly.


# securityContext defines privilege and access control settings for a Pod
# or Container. Making sure that we dont run Neo4j as root user.
securityContext:
  runAsNonRoot: true
  runAsUser: 7474
  runAsGroup: 7474
  fsGroup: 7474

# Readiness probes will send a kill signal to the container if
# it fails enough times.  It's therefore very important
# that initialDelaySeconds give the cluster time to form, because
# if readiness probes start immediately after container start,
# they may end up not forming quickly enough and getting killed.
readinessProbe:
  failureThreshold: 2
  timeoutSeconds: 2
  periodSeconds: 1

# Liveness probes are set to know when to restart a container
livenessProbe:
  failureThreshold: 30
  timeoutSeconds: 2
  periodSeconds: 20

# Startup probes are used to know when a container application has started.
# If such a probe is configured, it disables liveness and readiness checks until it succeeds
startupProbe:
  failureThreshold: 2000
  periodSeconds: 25

# top level setting called ssl to match the "ssl" from "dbms.ssl.policy"
ssl:
  # setting per "connector" matching neo4j config
  bolt:
    privateKey:
      secretName:  # we set up the template to grab `private.key` from this secret
      subPath:  # we specify the privateKey value name to get from the secret
    publicCertificate:
      secretName:  # we set up the template to grab `public.crt` from this secret
      subPath:  # we specify the publicCertificate value name to get from the secret
    trustedCerts:
      sources: [ ] # a sources array for a projected volume - this allows someone to (relatively) easily mount multiple public certs from multiple secrets for example.
    revokedCerts:
      sources: [ ]  # a sources array for a projected volume
  https:
    privateKey:
      secretName:
      subPath:
    publicCertificate:
      secretName:
      subPath:
    trustedCerts:
      sources: [ ]
    revokedCerts:
      sources: [ ]

# A ClusterIP service for Neo4j driver applications and Neo4j Browser
neo4jService:
  # Annotations for the Neo4j service
  annotations: { }

# A headless service (DNS only) for cluster admin and ops tasks
adminService:
  # Annotations for the admin service
  annotations: { }
  # Neo4j ports to include in admin service
  ports:
    # Ports for Neo4j Cluster
    cluster:
      enabled: false
    # Ports for Neo4j metrics
    metrics:
      graphite:
        enabled: true
      prometheus:
        enabled: true
      jmx:
        enabled: false # jmx is disabled because it's not secure to enable it unless jmx authentication is configured in neo4j config

externalService:
  # Annotations for the external service
  annotations: { }

  # A reserved/static IP that you want the LoadBalancer to use (usually optional, depending on the load balancer implmentation)
  loadBalancerIP: NULL

  # Neo4j ports to include in external service
  ports:
    http:
      enabled: true #Set this to true to expose HTTP externally
    https:
      enabled: true #Set this to true to expose HTTPS externally
    bolt:
      enabled: true #Set this to true to expose BOLT externally
    backup:
      enabled: false #Set this to true to expose backup port externally (n.b. this could have security implications. Backup is not authenticated by default)

clusterDomain: "cluster.local"

podAntiAffinity: true
