{{ $password := include "neo4j.password" . | printf "neo4j/%v" | b64enc | quote }}

{{- $name := printf "%s-auth" .Release.Name }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) }}
{{- if $secret }}
{{ $password = index $secret.data "NEO4J_AUTH"| quote }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-auth"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ template "neo4j.appName" . }}"
type: Opaque
data:
  NEO4J_AUTH: {{ $password }}
