{{- $authDisabled := index .Values.config "dbms.security.auth_enabled" | default "" | regexMatch "(?i)no|false" -}}
{{- if not $authDisabled -}}
{{- $password := include "neo4j.password" . | printf "neo4j/%v" | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-auth"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ template "neo4j.appName" . }}"
type: Opaque
data:
  NEO4J_AUTH: "{{ $password }}"
{{- end -}}
