apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: "{{ .Release.Name }}-service-reader"
rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["services", "endpoints"]
      verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-service-binding"
subjects:
    - kind: ServiceAccount
      name: {{ .Release.Name }}
roleRef:
    # "roleRef" specifies the binding to a Role / ClusterRole
    kind: Role # this must be Role or ClusterRole
    name: {{ .Release.Name }}-service-reader # this must match the name of the Role or ClusterRole you wish to bind to
    apiGroup: rbac.authorization.k8s.io
