{{- if or .Values.logs.ipAddress .Values.logs.fileShare | or .Values.logs.capacity.storage | or .Values.logs.storageClassName -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  # n.b. persistent volumes don't seem to belong to namespaces
  name: "{{ .Release.Name }}-logs"
  labels:
    helm.neo4j.com/volume-role: "logs"
    app: "{{ template "neo4j.appName" . }}"
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: "{{ required "logs.capacity.storage is required (e.g. 1Ti)" .Values.logs.capacity.storage }}"
  nfs:
    path: "/{{ required "logs.fileShare is required" .Values.logs.fileShare }}"
    server: "{{ required "logs.ipAddress is required" .Values.logs.ipAddress }}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-logs"
  labels:
    helm.neo4j.com/volume-role: "logs"
    app: "{{ template "neo4j.appName" . }}"
spec:
  storageClassName: "{{ .Values.logs.storageClassName }}"
  volumeName: "{{ .Release.Name }}-logs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ required "logs.capacity.storage is required (e.g. 1Ti)" .Values.logs.capacity.storage }}"
{{- end }}
